library(tidyverse)
library(gganimate)
library(gifski)
theme_set(theme_classic())


load("data/table.Rdata")

# generate top n ranking by year group

anim_table <- table %>%
  dplyr::group_by(Season) %>%
  dplyr::mutate(
    rank = min_rank(-Points) * 1,
    Value_rel = Points / Points[rank == 1],
    Value_lbl = paste0(" ", Points)
  ) %>%
  dplyr::filter(rank <= 10) %>%
  dplyr::ungroup()

# create animated barchart

p <- ggplot2::ggplot(anim_table, aes(rank)) +
  ggplot2::geom_tile(aes(
    y = Points / 2,
    height = Points,
    width = 0.9,
    fill = "blue"
  ), alpha = 0.8, color = NA) +
  ggplot2::geom_text(aes(y = 0, label = paste(Team, " ")), size = 12, vjust = 0.2, hjust = 1) +
  ggplot2::geom_text(aes(y = Points, label = Value_lbl, hjust = 0)) +
  ggplot2::coord_flip(clip = "off", expand = FALSE) +
  ggplot2::scale_y_continuous(labels = scales::comma) +
  ggplot2::scale_x_reverse() +
  ggplot2::guides(color = FALSE, fill = FALSE) +
  ggplot2::labs(
    title = "{closest_state}", x = "", y = "Total Points",
    caption = "Source:  Github(jalapic/engsoccerdata) | Top tier points only, does not include mandatory points deductions | Plot generated by @dr_keithmcnulty"
  ) +
  ggplot2::theme(
    plot.title = element_text(color = "darkblue", face = "bold", hjust = 0, size = 30),
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    plot.margin = margin(2, 2, 1, 16, "cm")
  ) +
  gganimate::transition_states(SeasonLabel, transition_length = 4, state_length = 1) +
  gganimate::ease_aes("cubic-in-out")

# save as preferred rendered format

gganimate::animate(p, 200, fps = 5, duration = 220, width = 2000, height = 1200, renderer = ffmpeg_renderer("anim.mp4"))
